version: "3.3"
services:
  traefik:
    image: traefik:2.7
    command:
      - "--api"
      - "--entrypoints.http.address=:80"
      - "--providers.docker"
      - "--providers.docker.swarmmode"
      - "--providers.docker.exposedbydefault=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik-net
    ports:
      - 80:80
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik-net
        traefik.http.routers.traefik-http-router.rule: Host(`traefik.${DOMAIN_NAME}`)
        traefik.http.routers.traefik-http-router.entrypoints: http
        traefik.port: 8080
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  swarmpit:
    image: swarmpit/swarmpit:1.9
    environment:
      - SWARMPIT_DB=http://swarmpit_db:5984
      - SWARMPIT_INFLUXDB=http://swarmpit_influxdb:8086
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
      - traefik-net
    deploy:
      labels:
        traefik.enable: 'true'
        traefik.docker.network: traefik-net
        traefik.http.routers.swarmpit-http-router.rule: Host(`swarmpit.${DOMAIN_NAME}`)
        traefik.http.routers.swarmpit-http-router.entrypoints: http
        traefik.port: 8080
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
        reservations:
          cpus: '0.25'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  swarmpit_db:
    image: couchdb:2.3.0
    volumes:
      - db-data:/opt/couchdb/data
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 512M
        reservations:
          cpus: '0.15'
          memory: 256M
      placement:
        constraints:
          - node.role == manager

  swarmpit_influxdb:
    image: influxdb:1.7
    volumes:
     - influx-data:/var/lib/influxdb
    networks:
     - net
    logging:
      driver: json-file
    deploy:
      resources:
        reservations:
          cpus: '0.3'
          memory: 128M
        limits:
          cpus: '0.6'
          memory: 512M
      placement:
        constraints:
          - node.role == manager

  swarmpit_agent:
    image: swarmpit/agent:2.2
    environment:
      - EVENT_ENDPOINT=http://swarmpit:8080/events
      - HEALTH_CHECK_ENDPOINT=http://swarmpit:8080/version
      - DOCKER_API_VERSION=1.35
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - net
    deploy:
      mode: global
      labels:
        swarmpit.agent: 'true'
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M

  cluster_cleanup:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: docker system prune --all --force
    deploy:
      mode: global
      restart_policy:
        delay: 24h

networks:
  net:
    driver: overlay
  traefik-net:
    driver: overlay
    external: true

volumes:
  db-data:
    driver: local
  influx-data:
    driver: local
